name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: klimik/nestjs-app
      IMAGE_TAG: latest
      K8S_NAMESPACE: default

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || true

      - name: Run Unit Tests
        run: npm test || true

      - name: Build NestJS
        run: npm run build

      - name: Run Redis Integration Test
        run: |
          docker run -d --name redis-test -p 6379:6379 -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} redis:7 redis-server --requirepass "${{ secrets.REDIS_PASSWORD }}"
          export REDIS_HOST=localhost
          export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          node dist/main.js &
          APP_PID=$!
          sleep 5
          RESPONSE=$(curl -s http://localhost:3000/redis)
          echo "Redis test response: $RESPONSE"
          if [[ "$RESPONSE" != *'"status":true'* ]]; then
            echo "Redis integration test failed"
            kill $APP_PID
            docker rm -f redis-test
            exit 1
          fi
          kill $APP_PID
          docker rm -f redis-test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy manifests to GKE
        run: |
          kubectl config current-context
          kubectl get nodes
          kubectl apply -f k8s/
          kubectl rollout status deployment/nestjs-app -n $K8S_NAMESPACE
          kubectl rollout status deployment/redis -n $K8S_NAMESPACE
